kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-storage-statefulset-azurefile-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-azurefile
  storageClassName: ""